title: Abyssal Website
description: Abyssal Website
remote_theme: just-the-docs/just-the-docs

footer_content: "Copyright &copy; 2020-2024 Agent's SCP Foundation."



url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

