title: Abyssal Website
description: Abyssal Website
remote_theme: just-the-docs/just-the-docs

color_scheme: scpf
logo: "/images/logos/foundation-logo.png"
footer_content: "Copyright &copy; 2020-2024 Agent's SCP Foundation."



url: https://just-the-docs.github.io
callouts:
  important:
    title: Important
    color: red
  caution:
    title: Caution
    color: yellow
  hint:
    title: Hint
    color: green
  information:
    title: Information
    color: blue

last_edit_timestamp: true
search_enabled: false

