title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: pmarsceill/just-the-docs

footer_content: "Copyright &copy; 2020-2024 Agent's SCP Foundation."

color_scheme: scpf

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

